"""Memory source type definitions."""
from __future__ import annotations
from enum import Enum


class MemorySourceType(str, Enum):
    BRODY_RUNTIME = "BRODY_RUNTIME"
    GRAPHITI_GRAPH = "GRAPHITI_GRAPH"
    DOCUMENT_INGESTION = "DOCUMENT_INGESTION"
    CONTEXT_PACKET = "CONTEXT_PACKET"
    FEEDBACK_CAPTURE = "FEEDBACK_CAPTURE"
    OPERATOR_SESSION = "OPERATOR_SESSION"
    HUMAN_REVIEW = "HUMAN_REVIEW"
    UNKNOWN = "UNKNOWN"


class MemoryCandidateStatus(str, Enum):
    CAPTURED = "CAPTURED"
    HASHED = "HASHED"
    CANDIDATE_ONLY = "CANDIDATE_ONLY"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    FROZEN = "FROZEN"
    REJECTED = "REJECTED"
    PROMOTION_READY = "PROMOTION_READY"
    PROMOTED_MANUAL_ONLY = "PROMOTED_MANUAL_ONLY"
