"""
scripts/audit_filesystem_path_exposure_p69.py — P69 filesystem & path exposure audit.

AUDIT ONLY — ne modifie aucun fichier source, ne corrige rien.
"""
import json
from pathlib import Path

ROOT = Path(__file__).parent.parent

# ─── Catalogue filesystem_matrix ─────────────────────────────────────────────
# Construit manuellement depuis le scan des surfaces (grep + lecture ciblée).
# Chaque entrée = un fichier ou une surface avec ses propriétés filesystem.

FILESYSTEM_MATRIX = [
    # ── apps/obsidia_api ──────────────────────────────────────────────────────
    {
        "path": "apps/obsidia_api/audit_middleware.py",
        "surface": "apps/obsidia_api",
        "detected_terms": ["open(...,'a')", "json.dumps", "Path.mkdir", ".write(", "audit_logs/"],
        "read_patterns": [],
        "write_patterns": ["audit_logs/http_audit_{date}.jsonl", "_LOG_DIR.mkdir(parents=True)"],
        "delete_patterns": [],
        "path_exposure": False,
        "source_excerpt_exposure": False,
        "absolute_path_exposure": False,
        "writes_local_audit": True,
        "writes_artifact": False,
        "writes_report": False,
        "writes_manifest": False,
        "writes_freeze": False,
        "writes_canonical_memory": False,
        "reads_source_pack": False,
        "reads_tmp_core_import": False,
        "reads_freezes": False,
        "category": "LOCAL_AUDIT_WRITE",
        "risk_level": "LOW",
        "reason": "AuditMiddleware — async append-only jsonl per request. Documented boundary. Aucun write canonique.",
        "next_action": "OK_CLASSIFIED",
    },
    {
        "path": "periphery/event_bus.py",
        "surface": "periphery",
        "detected_terms": ["open(...,'a')", "json.dumps", "Path.mkdir", ".write(", "audit_logs/event_bus_{date}.jsonl"],
        "read_patterns": [],
        "write_patterns": ["audit_logs/event_bus_{date}.jsonl"],
        "delete_patterns": [],
        "path_exposure": False,
        "source_excerpt_exposure": False,
        "absolute_path_exposure": False,
        "writes_local_audit": True,
        "writes_artifact": False,
        "writes_report": False,
        "writes_manifest": False,
        "writes_freeze": False,
        "writes_canonical_memory": False,
        "reads_source_pack": False,
        "reads_tmp_core_import": False,
        "reads_freezes": False,
        "category": "LOCAL_AUDIT_WRITE",
        "risk_level": "LOW",
        "reason": "AuditEventWriter — async persistence, never blocks. Documented in header. audit_logs/ only.",
        "next_action": "OK_CLASSIFIED",
    },
    {
        "path": "periphery/world_calls/world_action_bus.py",
        "surface": "periphery",
        "detected_terms": ["open(...,'a')", "json.dumps", "world_action_bus.jsonl"],
        "read_patterns": [],
        "write_patterns": ["audit/world_action_bus.jsonl"],
        "delete_patterns": [],
        "path_exposure": False,
        "source_excerpt_exposure": False,
        "absolute_path_exposure": False,
        "writes_local_audit": True,
        "writes_artifact": False,
        "writes_report": False,
        "writes_manifest": False,
        "writes_freeze": False,
        "writes_canonical_memory": False,
        "reads_source_pack": False,
        "reads_tmp_core_import": False,
        "reads_freezes": False,
        "category": "LOCAL_AUDIT_WRITE",
        "risk_level": "LOW",
        "reason": "WorldActionBus — append-only dry_run journal. blocked=True par défaut. Hash mismatch préexistant P65.",
        "next_action": "OK_PREEXISTING_DRIFT_DOCUMENTED",
    },
    {
        "path": "audit/world_action_bus.jsonl",
        "surface": "audit",
        "detected_terms": ["jsonl", "world_action_bus"],
        "read_patterns": ["lecture par verify_recursive_manifest.py"],
        "write_patterns": ["via periphery/world_calls/world_action_bus.py"],
        "delete_patterns": [],
        "path_exposure": False,
        "source_excerpt_exposure": False,
        "absolute_path_exposure": False,
        "writes_local_audit": True,
        "writes_artifact": False,
        "writes_report": False,
        "writes_manifest": False,
        "writes_freeze": False,
        "writes_canonical_memory": False,
        "reads_source_pack": False,
        "reads_tmp_core_import": False,
        "reads_freezes": False,
        "category": "LOCAL_AUDIT_WRITE",
        "risk_level": "LOW",
        "reason": "HASH_MISMATCH_PREEXISTING_P65 — drift documenté. Append-only dry_run log.",
        "next_action": "OK_PREEXISTING_DRIFT_DOCUMENTED",
    },
    {
        "path": "apps/obsidia_api/brody_freeze_metrics_snapshot.py",
        "surface": "apps/obsidia_api",
        "detected_terms": ["Path(manifest_path)", "manifest_path", "_load_manifest"],
        "read_patterns": ["MANIFEST json depuis freeze pointers"],
        "write_patterns": [],
        "delete_patterns": [],
        "path_exposure": False,
        "source_excerpt_exposure": False,
        "absolute_path_exposure": False,
        "writes_local_audit": False,
        "writes_artifact": False,
        "writes_report": False,
        "writes_manifest": False,
        "writes_freeze": False,
        "writes_canonical_memory": False,
        "reads_source_pack": False,
        "reads_tmp_core_import": False,
        "reads_freezes": True,
        "category": "LOCAL_FILE_READ",
        "risk_level": "LOW",
        "reason": "Reads manifest pointers from freeze snapshots. Read-only. Path relative.",
        "next_action": "OK_CLASSIFIED",
    },
    {
        "path": "apps/obsidia_api/brody_candidate_memory_adapter.py",
        "surface": "apps/obsidia_api",
        "detected_terms": ["_local_audits/memory_candidate_ledger.jsonl", "ledger_path.exists()"],
        "read_patterns": ["_local_audits/memory_candidate_ledger.jsonl"],
        "write_patterns": [],
        "delete_patterns": [],
        "path_exposure": False,
        "source_excerpt_exposure": False,
        "absolute_path_exposure": False,
        "writes_local_audit": False,
        "writes_artifact": False,
        "writes_report": False,
        "writes_manifest": False,
        "writes_freeze": False,
        "writes_canonical_memory": False,
        "reads_source_pack": False,
        "reads_tmp_core_import": False,
        "reads_freezes": False,
        "category": "LOCAL_FILE_READ",
        "risk_level": "LOW",
        "reason": "Reads memory_candidate_ledger for advisory context. No write. Candidate-only boundary.",
        "next_action": "OK_CLASSIFIED",
    },
    {
        "path": "apps/obsidia_api/routes/source_runtime_status.py",
        "surface": "apps/obsidia_api/routes",
        "detected_terms": ["list_available_families_cached()", "get_cache_stats()", "build_brody_context_from_source_packs"],
        "read_patterns": ["runtime_wiring.source_runtime.*", "_source_packs via cache"],
        "write_patterns": [],
        "delete_patterns": [],
        "path_exposure": False,
        "source_excerpt_exposure": True,
        "absolute_path_exposure": False,
        "writes_local_audit": False,
        "writes_artifact": False,
        "writes_report": False,
        "writes_manifest": False,
        "writes_freeze": False,
        "writes_canonical_memory": False,
        "reads_source_pack": True,
        "reads_tmp_core_import": False,
        "reads_freezes": False,
        "category": "SOURCE_EXCERPT_REVIEW",
        "risk_level": "MEDIUM",
        "reason": "POST /preview expose build_brody_context_from_source_packs() sans auth. Contenu source pack potentiellement visible. No write.",
        "next_action": "REVIEW_P70_ADD_AUTH",
    },
    {
        "path": "apps/obsidia_api/routes/os_map.py",
        "surface": "apps/obsidia_api/routes",
        "detected_terms": ["route_capability_path", "CAPABILITY_TAXONOMY", "build_runtime_inventory_graph"],
        "read_patterns": ["runtime_wiring.source_runtime capability maps"],
        "write_patterns": [],
        "delete_patterns": [],
        "path_exposure": False,
        "source_excerpt_exposure": True,
        "absolute_path_exposure": False,
        "writes_local_audit": False,
        "writes_artifact": False,
        "writes_report": False,
        "writes_manifest": False,
        "writes_freeze": False,
        "writes_canonical_memory": False,
        "reads_source_pack": True,
        "reads_tmp_core_import": False,
        "reads_freezes": False,
        "category": "SOURCE_EXCERPT_REVIEW",
        "risk_level": "MEDIUM",
        "reason": "Expose capability taxonomy + runtime inventory map. No auth. SOURCE_EXPOSURE_REVIEW P68.",
        "next_action": "REVIEW_P70_ADD_AUTH",
    },
    # ── scripts/ ──────────────────────────────────────────────────────────────
    {
        "path": "scripts/generate_recursive_manifest.py",
        "surface": "scripts",
        "detected_terms": ["open('MANIFEST_SHA256_RECURSIVE.json','w')", "open('MANIFEST_SHA256_RECURSIVE_ROOT.txt','w')", "json.dump", "os.walk"],
        "read_patterns": ["os.walk('.') — tous les fichiers trackés"],
        "write_patterns": ["MANIFEST_SHA256_RECURSIVE.json", "MANIFEST_SHA256_RECURSIVE_ROOT.txt"],
        "delete_patterns": [],
        "path_exposure": False,
        "source_excerpt_exposure": False,
        "absolute_path_exposure": False,
        "writes_local_audit": False,
        "writes_artifact": False,
        "writes_report": False,
        "writes_manifest": True,
        "writes_freeze": False,
        "writes_canonical_memory": False,
        "reads_source_pack": False,
        "reads_tmp_core_import": False,
        "reads_freezes": False,
        "category": "MANIFEST_WRITE",
        "risk_level": "LOW",
        "reason": "Génère manifest SHA-256 root-level. Script standalone, non appelé depuis API. Classifié MANIFEST_WRITE.",
        "next_action": "OK_CLASSIFIED",
    },
    {
        "path": "scripts/verify_recursive_manifest.py",
        "surface": "scripts",
        "detected_terms": ["open('MANIFEST_SHA256_RECURSIVE.json')", "sha256", "os.walk"],
        "read_patterns": ["MANIFEST_SHA256_RECURSIVE.json", "os.walk('.') — tous les fichiers"],
        "write_patterns": [],
        "delete_patterns": [],
        "path_exposure": False,
        "source_excerpt_exposure": False,
        "absolute_path_exposure": False,
        "writes_local_audit": False,
        "writes_artifact": False,
        "writes_report": False,
        "writes_manifest": False,
        "writes_freeze": False,
        "writes_canonical_memory": False,
        "reads_source_pack": False,
        "reads_tmp_core_import": False,
        "reads_freezes": False,
        "category": "LOCAL_FILE_READ",
        "risk_level": "NONE",
        "reason": "Vérifie le manifest SHA256. Read-only. Ne corrige pas les drifts.",
        "next_action": "OK_CLASSIFIED",
    },
    {
        "path": "scripts/check_forbidden_content.py",
        "surface": "scripts",
        "detected_terms": ["open(file)", "rglob", "glob"],
        "read_patterns": ["scan tous les fichiers .py/.json/.md du repo"],
        "write_patterns": [],
        "delete_patterns": [],
        "path_exposure": False,
        "source_excerpt_exposure": False,
        "absolute_path_exposure": False,
        "writes_local_audit": False,
        "writes_artifact": False,
        "writes_report": False,
        "writes_manifest": False,
        "writes_freeze": False,
        "writes_canonical_memory": False,
        "reads_source_pack": False,
        "reads_tmp_core_import": False,
        "reads_freezes": False,
        "category": "LOCAL_FILE_READ",
        "risk_level": "NONE",
        "reason": "Audit script read-only. Scan forbidden patterns. Aucun write.",
        "next_action": "OK_CLASSIFIED",
    },
    {
        "path": "scripts/audit_boundary_semantic_split_p67.py",
        "surface": "scripts",
        "detected_terms": ["write_text", "json.dumps", "rglob"],
        "read_patterns": ["scan 12 surfaces repo"],
        "write_patterns": ["docs/core_import/P67_BOUNDARY_SEMANTIC_SPLIT_AUDIT.json"],
        "delete_patterns": [],
        "path_exposure": False,
        "source_excerpt_exposure": False,
        "absolute_path_exposure": False,
        "writes_local_audit": False,
        "writes_artifact": True,
        "writes_report": False,
        "writes_manifest": False,
        "writes_freeze": False,
        "writes_canonical_memory": False,
        "reads_source_pack": False,
        "reads_tmp_core_import": False,
        "reads_freezes": False,
        "category": "ARTIFACT_WRITE",
        "risk_level": "NONE",
        "reason": "Audit P67 — écrit docs/core_import uniquement. AUDIT_ONLY classifié.",
        "next_action": "OK_CLASSIFIED",
    },
    {
        "path": "scripts/audit_api_auth_route_exposure_p68.py",
        "surface": "scripts",
        "detected_terms": ["write_text", "json.dumps"],
        "read_patterns": ["catalogue statique routes"],
        "write_patterns": ["docs/core_import/P68_API_AUTH_ROUTE_EXPOSURE_AUDIT.json"],
        "delete_patterns": [],
        "path_exposure": False,
        "source_excerpt_exposure": False,
        "absolute_path_exposure": False,
        "writes_local_audit": False,
        "writes_artifact": True,
        "writes_report": False,
        "writes_manifest": False,
        "writes_freeze": False,
        "writes_canonical_memory": False,
        "reads_source_pack": False,
        "reads_tmp_core_import": False,
        "reads_freezes": False,
        "category": "ARTIFACT_WRITE",
        "risk_level": "NONE",
        "reason": "Audit P68 — écrit docs/core_import uniquement. AUDIT_ONLY classifié.",
        "next_action": "OK_CLASSIFIED",
    },
    # ── proofs/ ───────────────────────────────────────────────────────────────
    {
        "path": "proofs/PROOFKIT_REPORT.json",
        "surface": "proofs",
        "detected_terms": ["json manifest", "proof report"],
        "read_patterns": ["lu par verify_all.py"],
        "write_patterns": ["écrit par proofs/generate_proofkit_report.py si présent"],
        "delete_patterns": [],
        "path_exposure": False,
        "source_excerpt_exposure": False,
        "absolute_path_exposure": False,
        "writes_local_audit": False,
        "writes_artifact": False,
        "writes_report": True,
        "writes_manifest": True,
        "writes_freeze": False,
        "writes_canonical_memory": False,
        "reads_source_pack": False,
        "reads_tmp_core_import": False,
        "reads_freezes": False,
        "category": "MANIFEST_WRITE",
        "risk_level": "LOW",
        "reason": "HASH_MISMATCH_PREEXISTING_P65 — drift documenté. Ne pas corriger dans P69.",
        "next_action": "OK_PREEXISTING_DRIFT_DOCUMENTED",
    },
    # ── periphery/ writes ─────────────────────────────────────────────────────
    {
        "path": "periphery/memory/memory_candidate_ledger.py",
        "surface": "periphery",
        "detected_terms": ["open(...,'a')", ".write(", "ledger"],
        "read_patterns": ["lit le ledger pour advisory"],
        "write_patterns": ["_local_audits/memory_candidate_ledger.jsonl"],
        "delete_patterns": [],
        "path_exposure": False,
        "source_excerpt_exposure": False,
        "absolute_path_exposure": False,
        "writes_local_audit": True,
        "writes_artifact": False,
        "writes_report": False,
        "writes_manifest": False,
        "writes_freeze": False,
        "writes_canonical_memory": False,
        "reads_source_pack": False,
        "reads_tmp_core_import": False,
        "reads_freezes": False,
        "category": "LOCAL_AUDIT_WRITE",
        "risk_level": "LOW",
        "reason": "Memory candidate ledger — append-only, advisory. memory_write=False dans boundary.",
        "next_action": "OK_CLASSIFIED",
    },
    {
        "path": "periphery/world_calls/ticket_store.py",
        "surface": "periphery",
        "detected_terms": ["open(...,'w')", "json.dump", "ticket"],
        "read_patterns": ["lit tickets existants"],
        "write_patterns": ["tickets JSON local"],
        "delete_patterns": [],
        "path_exposure": False,
        "source_excerpt_exposure": False,
        "absolute_path_exposure": False,
        "writes_local_audit": True,
        "writes_artifact": False,
        "writes_report": False,
        "writes_manifest": False,
        "writes_freeze": False,
        "writes_canonical_memory": False,
        "reads_source_pack": False,
        "reads_tmp_core_import": False,
        "reads_freezes": False,
        "category": "LOCAL_AUDIT_WRITE",
        "risk_level": "LOW",
        "reason": "Ticket store local — dry_run_only, sovereign ticket tracking. Non accessible API publique.",
        "next_action": "OK_CLASSIFIED",
    },
    {
        "path": "periphery/gencoin_ledger.py",
        "surface": "periphery",
        "detected_terms": ["open(...,'a')", ".write(", "gencoin"],
        "read_patterns": [],
        "write_patterns": ["gencoin ledger local"],
        "delete_patterns": [],
        "path_exposure": False,
        "source_excerpt_exposure": False,
        "absolute_path_exposure": False,
        "writes_local_audit": True,
        "writes_artifact": False,
        "writes_report": False,
        "writes_manifest": False,
        "writes_freeze": False,
        "writes_canonical_memory": False,
        "reads_source_pack": False,
        "reads_tmp_core_import": False,
        "reads_freezes": False,
        "category": "LOCAL_AUDIT_WRITE",
        "risk_level": "LOW",
        "reason": "Gencoin ledger — append-only local. Non exposé publiquement. Dry-run only.",
        "next_action": "OK_CLASSIFIED",
    },
    {
        "path": "periphery/interface/interface_event_log.py",
        "surface": "periphery",
        "detected_terms": ["open(...,'a')", ".write(", "event_log"],
        "read_patterns": [],
        "write_patterns": ["interface event log local"],
        "delete_patterns": [],
        "path_exposure": False,
        "source_excerpt_exposure": False,
        "absolute_path_exposure": False,
        "writes_local_audit": True,
        "writes_artifact": False,
        "writes_report": False,
        "writes_manifest": False,
        "writes_freeze": False,
        "writes_canonical_memory": False,
        "reads_source_pack": False,
        "reads_tmp_core_import": False,
        "reads_freezes": False,
        "category": "LOCAL_AUDIT_WRITE",
        "risk_level": "LOW",
        "reason": "Interface event log — append-only. Advisory. Non exposé publiquement.",
        "next_action": "OK_CLASSIFIED",
    },
    {
        "path": "periphery/brody_memory_readonly/session_trace_ledger/brody_session_trace_ledger_readonly_v1_6_3.py",
        "surface": "periphery",
        "detected_terms": ["open(...,'a')", ".write(", "session_trace"],
        "read_patterns": [],
        "write_patterns": ["session trace local readonly"],
        "delete_patterns": [],
        "path_exposure": False,
        "source_excerpt_exposure": False,
        "absolute_path_exposure": False,
        "writes_local_audit": True,
        "writes_artifact": False,
        "writes_report": False,
        "writes_manifest": False,
        "writes_freeze": False,
        "writes_canonical_memory": False,
        "reads_source_pack": False,
        "reads_tmp_core_import": False,
        "reads_freezes": False,
        "category": "LOCAL_AUDIT_WRITE",
        "risk_level": "LOW",
        "reason": "SRL session trace ledger — readonly boundary. memory_write=False. Trace locale uniquement.",
        "next_action": "OK_CLASSIFIED",
    },
    # ── tests/ os.remove ──────────────────────────────────────────────────────
    {
        "path": "tests/test_seal_tamper.py",
        "surface": "tests",
        "detected_terms": ["os.remove", "unlink"],
        "read_patterns": [],
        "write_patterns": [],
        "delete_patterns": ["os.remove (test fixture tamper simulation)"],
        "path_exposure": False,
        "source_excerpt_exposure": False,
        "absolute_path_exposure": False,
        "writes_local_audit": False,
        "writes_artifact": False,
        "writes_report": False,
        "writes_manifest": False,
        "writes_freeze": False,
        "writes_canonical_memory": False,
        "reads_source_pack": False,
        "reads_tmp_core_import": False,
        "reads_freezes": False,
        "category": "TEST_FIXTURE_WRITE",
        "risk_level": "LOW",
        "reason": "Test fixture pour simuler tamper sur seal. os.remove sur copie de test uniquement. Non exécuté en prod.",
        "next_action": "OK_TEST_FIXTURE_ONLY",
    },
    # ── _source_packs / _tmp_core_import / _freezes / .local_audits ──────────
    {
        "path": "_source_packs/",
        "surface": "_source_packs",
        "detected_terms": ["source pack data"],
        "read_patterns": ["lu via runtime_wiring.source_runtime cache"],
        "write_patterns": [],
        "delete_patterns": [],
        "path_exposure": False,
        "source_excerpt_exposure": False,
        "absolute_path_exposure": False,
        "writes_local_audit": False,
        "writes_artifact": False,
        "writes_report": False,
        "writes_manifest": False,
        "writes_freeze": False,
        "writes_canonical_memory": False,
        "reads_source_pack": True,
        "reads_tmp_core_import": False,
        "reads_freezes": False,
        "category": "SOURCE_PACK_READ",
        "risk_level": "LOW",
        "reason": "Archive source packs. 51 fichiers (0 py). Lu via source_runtime cache — pas exposé direct API.",
        "next_action": "OK_CLASSIFIED",
    },
    {
        "path": "_tmp_core_import/",
        "surface": "_tmp_core_import",
        "detected_terms": ["import archive", "tmp"],
        "read_patterns": ["archive temporaire d'import P-paliers"],
        "write_patterns": [],
        "delete_patterns": [],
        "path_exposure": False,
        "source_excerpt_exposure": False,
        "absolute_path_exposure": False,
        "writes_local_audit": False,
        "writes_artifact": False,
        "writes_report": False,
        "writes_manifest": False,
        "writes_freeze": False,
        "writes_canonical_memory": False,
        "reads_source_pack": False,
        "reads_tmp_core_import": True,
        "reads_freezes": False,
        "category": "SOURCE_PACK_READ",
        "risk_level": "LOW",
        "reason": "Archive import temporaire. 368 fichiers (137 py). Non importé en runtime — archive seulement.",
        "next_action": "OK_CLASSIFIED",
    },
    {
        "path": "_freezes/",
        "surface": "_freezes",
        "detected_terms": ["freeze snapshots", "manifest pointers"],
        "read_patterns": ["lu par brody_freeze_metrics_snapshot.py via pointers"],
        "write_patterns": [],
        "delete_patterns": [],
        "path_exposure": False,
        "source_excerpt_exposure": False,
        "absolute_path_exposure": False,
        "writes_local_audit": False,
        "writes_artifact": False,
        "writes_report": False,
        "writes_manifest": False,
        "writes_freeze": False,
        "writes_canonical_memory": False,
        "reads_source_pack": False,
        "reads_tmp_core_import": False,
        "reads_freezes": True,
        "category": "LOCAL_FILE_READ",
        "risk_level": "LOW",
        "reason": "Freeze snapshots. 2986 fichiers (0 py). Lecture via pointers pour freeze_metrics. Non exposé API publique.",
        "next_action": "OK_CLASSIFIED",
    },
    {
        "path": ".local_audits/",
        "surface": ".local_audits",
        "detected_terms": ["jsonl", "audit logs", "memory_candidate_ledger"],
        "read_patterns": ["lu par brody_candidate_memory_adapter.py"],
        "write_patterns": ["alimenté par memory_candidate_ledger.py"],
        "delete_patterns": [],
        "path_exposure": False,
        "source_excerpt_exposure": False,
        "absolute_path_exposure": False,
        "writes_local_audit": True,
        "writes_artifact": False,
        "writes_report": False,
        "writes_manifest": False,
        "writes_freeze": False,
        "writes_canonical_memory": False,
        "reads_source_pack": False,
        "reads_tmp_core_import": False,
        "reads_freezes": False,
        "category": "LOCAL_AUDIT_WRITE",
        "risk_level": "LOW",
        "reason": "Répertoire audit local. 46 fichiers (3 py). Logs candidats mémoire. Non exposé API.",
        "next_action": "OK_CLASSIFIED",
    },
    # ── audit/RUN_METRICS_PALIER_LAST.json — absolute path dans données ───────
    {
        "path": "audit/RUN_METRICS_PALIER_LAST.json",
        "surface": "audit",
        "detected_terms": ["C:\\Users\\User\\Desktop\\", "absolute path in stored data"],
        "read_patterns": [],
        "write_patterns": ["écrit par des outils de run sigma"],
        "delete_patterns": [],
        "path_exposure": True,
        "source_excerpt_exposure": False,
        "absolute_path_exposure": True,
        "writes_local_audit": True,
        "writes_artifact": False,
        "writes_report": False,
        "writes_manifest": False,
        "writes_freeze": False,
        "writes_canonical_memory": False,
        "reads_source_pack": False,
        "reads_tmp_core_import": False,
        "reads_freezes": False,
        "category": "ABSOLUTE_PATH_EXPOSURE",
        "risk_level": "MEDIUM",
        "reason": "Contient C:\\Users\\User\\Desktop\\... dans stdout capturé des runs sigma. Données de test archivées. Ne pas exposer via API.",
        "next_action": "REVIEW_P70_NOT_EXPOSE_VIA_API",
    },
    # ── sigma/sigma_config.json — absolu path in stdout ──────────────────────
    {
        "path": "sigma/sigma_config.json",
        "surface": "sigma",
        "detected_terms": ["Config source : C:\\\\Users\\\\User\\\\Desktop\\\\"],
        "read_patterns": ["lu par sigma run_pipeline.py"],
        "write_patterns": [],
        "delete_patterns": [],
        "path_exposure": True,
        "source_excerpt_exposure": False,
        "absolute_path_exposure": True,
        "writes_local_audit": False,
        "writes_artifact": False,
        "writes_report": False,
        "writes_manifest": False,
        "writes_freeze": False,
        "writes_canonical_memory": False,
        "reads_source_pack": False,
        "reads_tmp_core_import": False,
        "reads_freezes": False,
        "category": "ABSOLUTE_PATH_EXPOSURE",
        "risk_level": "MEDIUM",
        "reason": "Chemin absolu dans stdout sigma output (sigma/sigma_config.json path résolu). Ne pas exposer dans API response.",
        "next_action": "REVIEW_P70_MASK_PATH_IN_RESPONSE",
    },
    # ── scripts/f30_2_copy_v5_readonly_module.py ─────────────────────────────
    {
        "path": "scripts/f30_2_copy_v5_readonly_module.py",
        "surface": "scripts",
        "detected_terms": ["shutil.copy", "shutil.copyfile"],
        "read_patterns": [],
        "write_patterns": ["copie module v5 readonly"],
        "delete_patterns": [],
        "path_exposure": False,
        "source_excerpt_exposure": False,
        "absolute_path_exposure": False,
        "writes_local_audit": False,
        "writes_artifact": False,
        "writes_report": False,
        "writes_manifest": False,
        "writes_freeze": False,
        "writes_canonical_memory": False,
        "reads_source_pack": False,
        "reads_tmp_core_import": True,
        "reads_freezes": False,
        "category": "SOURCE_NORMALIZATION_WRITE",
        "risk_level": "LOW",
        "reason": "Script d'import contrôlé — copie module v5 dans chemin readonly. Script one-shot, non appelé en runtime.",
        "next_action": "OK_CLASSIFIED",
    },
    # ── periphery/brody_memory_readonly/brody_local_command_gate_readonly ─────
    {
        "path": "periphery/brody_memory_readonly/brody_local_command_gate_readonly/brody_local_command_gate_readonly_v1.py",
        "surface": "periphery",
        "detected_terms": ["os.remove"],
        "read_patterns": [],
        "write_patterns": [],
        "delete_patterns": ["os.remove — cleanup gate test file"],
        "path_exposure": False,
        "source_excerpt_exposure": False,
        "absolute_path_exposure": False,
        "writes_local_audit": False,
        "writes_artifact": False,
        "writes_report": False,
        "writes_manifest": False,
        "writes_freeze": False,
        "writes_canonical_memory": False,
        "reads_source_pack": False,
        "reads_tmp_core_import": False,
        "reads_freezes": False,
        "category": "TEST_FIXTURE_WRITE",
        "risk_level": "LOW",
        "reason": "Gate local command test — os.remove sur fichier test gate uniquement. Smoke test local.",
        "next_action": "OK_TEST_FIXTURE_ONLY",
    },
    # ── runtime_wiring/ — readonly, gelé P56E ─────────────────────────────────
    {
        "path": "runtime_wiring/",
        "surface": "runtime_wiring",
        "detected_terms": ["source_runtime cache", "capability maps"],
        "read_patterns": ["lu via runtime_wiring.source_runtime.* imports (si disponible)"],
        "write_patterns": [],
        "delete_patterns": [],
        "path_exposure": False,
        "source_excerpt_exposure": False,
        "absolute_path_exposure": False,
        "writes_local_audit": False,
        "writes_artifact": False,
        "writes_report": False,
        "writes_manifest": False,
        "writes_freeze": False,
        "writes_canonical_memory": False,
        "reads_source_pack": True,
        "reads_tmp_core_import": False,
        "reads_freezes": False,
        "category": "LOCAL_FILE_READ",
        "risk_level": "NONE",
        "reason": "Gelé P56E. 111 fichiers. Lecture uniquement depuis routes (via ImportError guard). Aucun write.",
        "next_action": "OK_FROZEN_P56E",
    },
    # ── docs/core_import/ ─────────────────────────────────────────────────────
    {
        "path": "docs/core_import/",
        "surface": "docs",
        "detected_terms": ["P65_*.json", "P66_*.md", "P67_*", "P68_*"],
        "read_patterns": ["lu par tests/test_p*"],
        "write_patterns": ["écrit par scripts/audit_*.py"],
        "delete_patterns": [],
        "path_exposure": False,
        "source_excerpt_exposure": False,
        "absolute_path_exposure": False,
        "writes_local_audit": False,
        "writes_artifact": False,
        "writes_report": True,
        "writes_manifest": False,
        "writes_freeze": False,
        "writes_canonical_memory": False,
        "reads_source_pack": False,
        "reads_tmp_core_import": False,
        "reads_freezes": False,
        "category": "REPORT_WRITE",
        "risk_level": "NONE",
        "reason": "Rapports d'audit P-paliers. 883 fichiers doc. Classifiés REPORT_WRITE. Non exposés API publique.",
        "next_action": "OK_CLASSIFIED",
    },
]

# ─── Build category counts ────────────────────────────────────────────────────
def _build_counts(matrix):
    cc = {}
    for e in matrix:
        cat = e["category"]
        cc[cat] = cc.get(cat, 0) + 1
    return dict(sorted(cc.items(), key=lambda x: -x[1]))


def _bucket(matrix, category):
    return [e["path"] for e in matrix if e["category"] == category]


def main():
    category_counts = _build_counts(FILESYSTEM_MATRIX)

    filesystem_model = {
        "canonical_memory_write": "Écriture mémoire canonique Brody/session. INTERDIT sauf gate explicite humain KX108_ONLY.",
        "local_audit_write": "Écriture .jsonl/.log audit local. AUTORISÉ si classifié (audit_logs/, world_action_bus.jsonl, ledgers).",
        "artifact_write": "Écriture rapport JSON/MD par scripts d'audit. AUTORISÉ dans docs/core_import/ uniquement.",
        "pseudo_output_log_write": "Écriture log pseudo-output (stdout redirect). REVIEW si path exposé.",
        "report_write": "Écriture narrative MD/JSON dans docs/. AUTORISÉ.",
        "manifest_write": "Écriture manifest SHA256. AUTORISÉ dans scripts/ et root seulement, jamais hidden.",
        "source_normalization_write": "Copie de module source dans import contrôlé. AUTORISÉ si script one-shot.",
        "freeze_write": "Écriture snapshot freeze. AUTORISÉ uniquement via opérateur. _freezes/ est archive.",
        "test_fixture_write": "Écriture/suppression test fixture. AUTORISÉ dans tests/ uniquement, jamais en runtime.",
        "temp_write": "Écriture temp/swap. REVIEW selon destination.",
        "dangerous_path_write": "Écriture hors chemins classifiés. INTERDIT sans gate explicite.",
        "dangerous_delete": "os.remove / shutil.rmtree hors test fixture. INTERDIT en runtime.",
        "local_file_read": "Lecture fichiers locaux. AUTORISÉ si path relatif et source connue.",
        "source_pack_read": "Lecture depuis _source_packs/ via cache. AUTORISÉ si non exposé API publique.",
        "path_exposure": "Exposition chemin local dans réponse API. REVIEW — utiliser relative_path ou path_hash.",
        "source_excerpt_exposure": "Exposition contenu source pack dans réponse API. REVIEW — nécessite auth.",
        "absolute_path_exposure": "Chemin absolu Windows dans données stockées. REVIEW — ne pas exposer via API.",
    }

    focus_findings = [
        {
            "file": "apps/obsidia_api/audit_middleware.py",
            "finding": "Crée audit_logs/ + écrit http_audit_{date}.jsonl. LOCAL_AUDIT_WRITE classifié. Autorisé.",
            "category": "LOCAL_AUDIT_WRITE",
            "risk": "LOW",
            "action": "OK_CLASSIFIED",
        },
        {
            "file": "periphery/event_bus.py",
            "finding": "AuditEventWriter — async append audit_logs/event_bus_{date}.jsonl. LOCAL_AUDIT_WRITE. Autorisé.",
            "category": "LOCAL_AUDIT_WRITE",
            "risk": "LOW",
            "action": "OK_CLASSIFIED",
        },
        {
            "file": "periphery/world_calls/world_action_bus.py",
            "finding": "Écrit audit/world_action_bus.jsonl. Dry-run only. blocked=True défaut. Hash drift préexistant P65.",
            "category": "LOCAL_AUDIT_WRITE",
            "risk": "LOW",
            "action": "OK_PREEXISTING_DRIFT_DOCUMENTED",
        },
        {
            "file": "audit/world_action_bus.jsonl",
            "finding": "HASH_MISMATCH_PREEXISTING_P65. Append-only dry_run log. Ne pas corriger P69.",
            "category": "LOCAL_AUDIT_WRITE",
            "risk": "LOW",
            "action": "OK_PREEXISTING_DRIFT_DOCUMENTED",
        },
        {
            "file": "proofs/PROOFKIT_REPORT.json",
            "finding": "HASH_MISMATCH_PREEXISTING_P65. Manifest proof. Ne pas corriger P69.",
            "category": "MANIFEST_WRITE",
            "risk": "LOW",
            "action": "OK_PREEXISTING_DRIFT_DOCUMENTED",
        },
        {
            "file": "scripts/generate_recursive_manifest.py",
            "finding": "Écrit MANIFEST_SHA256_RECURSIVE.json + ROOT.txt. Script standalone. Classifié MANIFEST_WRITE.",
            "category": "MANIFEST_WRITE",
            "risk": "LOW",
            "action": "OK_CLASSIFIED",
        },
        {
            "file": "apps/obsidia_api/routes/source_runtime_status.py",
            "finding": "POST /preview expose build_brody_context_from_source_packs() sans auth. Source pack content potentiellement visible.",
            "category": "SOURCE_EXCERPT_REVIEW",
            "risk": "MEDIUM",
            "action": "REVIEW_P70_ADD_AUTH",
        },
        {
            "file": "apps/obsidia_api/routes/os_map.py",
            "finding": "Expose capability taxonomy + runtime inventory. No auth. SOURCE_EXCERPT_REVIEW.",
            "category": "SOURCE_EXCERPT_REVIEW",
            "risk": "MEDIUM",
            "action": "REVIEW_P70_ADD_AUTH",
        },
        {
            "file": "audit/RUN_METRICS_PALIER_LAST.json",
            "finding": "Contient C:\\Users\\User\\Desktop\\... dans stdout sigma archivé. ABSOLUTE_PATH_EXPOSURE dans données.",
            "category": "ABSOLUTE_PATH_EXPOSURE",
            "risk": "MEDIUM",
            "action": "REVIEW_P70_NOT_EXPOSE_VIA_API",
        },
        {
            "file": "sigma/sigma_config.json",
            "finding": "Chemin absolu résolu dans stdout sigma output. ABSOLUTE_PATH_EXPOSURE dans données capturées.",
            "category": "ABSOLUTE_PATH_EXPOSURE",
            "risk": "MEDIUM",
            "action": "REVIEW_P70_MASK_PATH_IN_RESPONSE",
        },
        {
            "file": "_source_packs/",
            "finding": "Archive source packs. 51 fichiers. Accès uniquement via source_runtime cache (readonly).",
            "category": "SOURCE_PACK_READ",
            "risk": "LOW",
            "action": "OK_CLASSIFIED",
        },
        {
            "file": "_tmp_core_import/",
            "finding": "Archive import temporaire. 368 fichiers (137 py). Non chargé en runtime API.",
            "category": "SOURCE_PACK_READ",
            "risk": "LOW",
            "action": "OK_CLASSIFIED",
        },
        {
            "file": "_freezes/",
            "finding": "Freeze snapshots. 2986 fichiers (0 py). Lu via pointers par brody_freeze_metrics_snapshot uniquement.",
            "category": "LOCAL_FILE_READ",
            "risk": "LOW",
            "action": "OK_CLASSIFIED",
        },
        {
            "file": ".local_audits/",
            "finding": "46 fichiers (3 py). Memory candidate logs. Append-only. Non exposé API.",
            "category": "LOCAL_AUDIT_WRITE",
            "risk": "LOW",
            "action": "OK_CLASSIFIED",
        },
    ]

    # Surface matrix summary
    surface_matrix = [
        {"surface": "apps/obsidia_api",    "files": 181, "reads": 3, "writes_local": 1, "reports": 0, "manifests": 0, "path_exposure": 0, "risk": "LOW"},
        {"surface": "apps/obsidia_api/routes", "files": 44, "reads": 2, "writes_local": 0, "reports": 0, "manifests": 0, "path_exposure": 0, "risk": "MEDIUM"},
        {"surface": "runtime_wiring",      "files": 111, "reads": 1, "writes_local": 0, "reports": 0, "manifests": 0, "path_exposure": 0, "risk": "NONE — FROZEN_P56E"},
        {"surface": "sigma",               "files": 136, "reads": 1, "writes_local": 0, "reports": 0, "manifests": 0, "path_exposure": 1, "risk": "MEDIUM — abs_path_stdout"},
        {"surface": "periphery",           "files": 3278, "reads": 2, "writes_local": 7, "reports": 0, "manifests": 0, "path_exposure": 0, "risk": "LOW"},
        {"surface": "connectors",          "files": 10,  "reads": 0, "writes_local": 0, "reports": 0, "manifests": 0, "path_exposure": 0, "risk": "LOW — CONNECTOR_EGRESS_REVIEWED_P68"},
        {"surface": "scripts",             "files": 258, "reads": 1, "writes_local": 0, "reports": 2, "manifests": 1, "path_exposure": 0, "risk": "LOW"},
        {"surface": "tools",               "files": 33,  "reads": 0, "writes_local": 0, "reports": 0, "manifests": 0, "path_exposure": 0, "risk": "NONE"},
        {"surface": "proofs",              "files": 188, "reads": 1, "writes_local": 0, "reports": 0, "manifests": 1, "path_exposure": 0, "risk": "LOW — DRIFT_PREEXISTING"},
        {"surface": "tests",               "files": 1030, "reads": 0, "writes_local": 0, "reports": 0, "manifests": 0, "path_exposure": 0, "risk": "LOW — TEST_FIXTURE_ONLY"},
        {"surface": "audit",               "files": 27,  "reads": 0, "writes_local": 2, "reports": 0, "manifests": 0, "path_exposure": 1, "risk": "MEDIUM — abs_path_in_data"},
        {"surface": "docs",                "files": 883, "reads": 0, "writes_local": 0, "reports": 4, "manifests": 0, "path_exposure": 0, "risk": "NONE"},
        {"surface": "_source_packs",       "files": 51,  "reads": 1, "writes_local": 0, "reports": 0, "manifests": 0, "path_exposure": 0, "risk": "LOW — ARCHIVE"},
        {"surface": "_tmp_core_import",    "files": 368, "reads": 1, "writes_local": 0, "reports": 0, "manifests": 0, "path_exposure": 0, "risk": "LOW — ARCHIVE"},
        {"surface": "_freezes",            "files": 2986, "reads": 1, "writes_local": 0, "reports": 0, "manifests": 0, "path_exposure": 0, "risk": "LOW — ARCHIVE"},
        {"surface": ".local_audits",       "files": 46,  "reads": 1, "writes_local": 1, "reports": 0, "manifests": 0, "path_exposure": 0, "risk": "LOW"},
    ]

    result = {
        "audit_id": "P69",
        "status": "P69_FILESYSTEM_PATH_EXPOSURE_AUDIT_READY",
        "mode": "AUDIT_ONLY",
        "source_patch_applied": False,
        "files_imported_count": 0,
        "filesystem_model": filesystem_model,
        "scanned_files_count": sum(s["files"] for s in surface_matrix),
        "filesystem_matrix": FILESYSTEM_MATRIX,
        "category_counts": category_counts,
        "surface_matrix": surface_matrix,
        "local_audit_write": _bucket(FILESYSTEM_MATRIX, "LOCAL_AUDIT_WRITE"),
        "artifact_write": _bucket(FILESYSTEM_MATRIX, "ARTIFACT_WRITE"),
        "report_write": _bucket(FILESYSTEM_MATRIX, "REPORT_WRITE"),
        "manifest_write": _bucket(FILESYSTEM_MATRIX, "MANIFEST_WRITE"),
        "source_normalization_write": _bucket(FILESYSTEM_MATRIX, "SOURCE_NORMALIZATION_WRITE"),
        "freeze_write": _bucket(FILESYSTEM_MATRIX, "FREEZE_WRITE"),
        "test_fixture_write": _bucket(FILESYSTEM_MATRIX, "TEST_FIXTURE_WRITE"),
        "temp_write": _bucket(FILESYSTEM_MATRIX, "TEMP_WRITE"),
        "dangerous_path_write": _bucket(FILESYSTEM_MATRIX, "DANGEROUS_PATH_WRITE"),
        "dangerous_delete": _bucket(FILESYSTEM_MATRIX, "DANGEROUS_DELETE"),
        "local_file_read": _bucket(FILESYSTEM_MATRIX, "LOCAL_FILE_READ"),
        "source_pack_read": _bucket(FILESYSTEM_MATRIX, "SOURCE_PACK_READ"),
        "path_exposure_review": _bucket(FILESYSTEM_MATRIX, "PATH_EXPOSURE_REVIEW"),
        "source_excerpt_review": _bucket(FILESYSTEM_MATRIX, "SOURCE_EXCERPT_REVIEW"),
        "absolute_path_exposure": _bucket(FILESYSTEM_MATRIX, "ABSOLUTE_PATH_EXPOSURE"),
        "safe_doc_reference": _bucket(FILESYSTEM_MATRIX, "SAFE_DOC_REFERENCE"),
        "safe_test_only": _bucket(FILESYSTEM_MATRIX, "SAFE_TEST_ONLY"),
        "unknown_requires_review": _bucket(FILESYSTEM_MATRIX, "UNKNOWN_REQUIRES_REVIEW"),
        "focus_findings": focus_findings,
        "preexisting_manifest_drift": [
            {"file": "audit/world_action_bus.jsonl", "status": "HASH_MISMATCH_PREEXISTING_P65"},
            {"file": "proofs/PROOFKIT_REPORT.json",  "status": "HASH_MISMATCH_PREEXISTING_P65"},
        ],
        "preexisting_test_debt": [
            {"test": "tests/test_invariants_against_engine.py", "reason": "ModuleNotFoundError: obsidia_os2"},
            {"test": "tests/sigma_stress_test.py",              "reason": "ModuleNotFoundError: agents.obsidia_sigma_v130"},
            {"test": "tests/test_agents_functional.py",         "reason": "ImportError: TradingState"},
            {"test": "tests/test_consensus_inprocess.py",       "reason": "ModuleNotFoundError: agents.run_pipeline"},
            {"test": "tests/test_sigma_v18_9.py",               "reason": "ModuleNotFoundError: agents.obsidia_sigma_v130"},
        ],
        "runtime_modified": False,
        "sigma_modified": False,
        "routes_modified": False,
        "srl_modified": False,
        "act_enabled": False,
        "memory_write_enabled": False,
        "graphiti_write_enabled": False,
        "neo4j_write_enabled": False,
        "kernel_mutation_enabled": False,
        "x108_merge_enabled": False,
        "next_step": "P70_NETWORK_EGRESS_AND_CONNECTORS_AUDIT",
    }

    out_path = ROOT / "docs" / "core_import" / "P69_FILESYSTEM_PATH_EXPOSURE_AUDIT.json"
    out_path.write_text(json.dumps(result, indent=2, ensure_ascii=True), encoding="utf-8")
    print(f"P69 JSON written: {out_path}")
    print(f"Files scanned total: {result['scanned_files_count']}")
    print(f"Matrix entries: {len(FILESYSTEM_MATRIX)}")
    print(f"Categories: {category_counts}")


if __name__ == "__main__":
    main()
