"""
R8-C3b2 — Obsidure Native Tooling Backend V1.

Native internal engineering-synthesis organ.

This is intentionally NEW tooling machinery.

It does NOT widen historical AgentObsidure's periphery-only
PYTHON_PATCH_PROPOSAL boundary.

Input:
    canonical prompt from C3a.

Brody-native:
    parses and structures readonly context.

Obsidure-native:
    applies an explicit bounded engineering strategy and returns the
    COMPLETE candidate source text.

V1 native strategy:
    INSERT_COMMENT_AFTER_MODULE_DOCSTRING

This strategy exists to prove the full internal generation rail with
real generated bytes while remaining narrow and auditable.

No external model/provider is used.

Authority:
    OBSIDURE_AUTHORITY = NONE
    DECISION_AUTHORITY = KX108_ONLY
"""

from __future__ import annotations

import ast
import json
import re

from typing import Any

from scripts.providers.brody_native_tooling_context_v1 import (
    BrodyNativeToolingContext,
    build_brody_native_tooling_context,
)

from scripts.providers.obsidia_tooling_generator_v1 import (
    ToolingBackendResult,
)


BACKEND_ID = (
    "OBSIDURE_NATIVE_TOOLING_V1"
)

MODEL_ID = (
    "obsidure-native-synthesis-v1"
)

OBSIDURE_AUTHORITY = "NONE"
DECISION_AUTHORITY = "KX108_ONLY"


_ALLOWED_TARGET_PREFIXES = (
    "scripts/obsidia_",
    "scripts/obsidure_",
    "scripts/providers/",
    "scripts/runtime_wiring/",
)


class ObsidureNativeToolingError(
    RuntimeError
):
    pass


def _validate_target(
    target_path: str,
) -> None:

    normalized = target_path.replace(
        "\\",
        "/",
    )

    if normalized != target_path:
        raise ObsidureNativeToolingError(
            "NATIVE_TARGET_BACKSLASH_REJECTED"
        )

    if not normalized.endswith(
        ".py"
    ):
        raise ObsidureNativeToolingError(
            "NATIVE_TARGET_PYTHON_ONLY"
        )

    if not any(
        normalized.startswith(
            prefix
        )
        for prefix in (
            _ALLOWED_TARGET_PREFIXES
        )
    ):
        raise ObsidureNativeToolingError(
            "NATIVE_TARGET_OUTSIDE_TOOLING_SCOPE"
        )


def _extract_edit_spec(
    objective: str,
) -> dict[str, Any]:

    marker = (
        "NATIVE_EDIT_JSON="
    )

    index = objective.rfind(
        marker
    )

    if index < 0:
        raise ObsidureNativeToolingError(
            "NATIVE_EDIT_SPEC_REQUIRED"
        )


    raw = objective[
        index
        + len(marker):
    ].strip()


    try:
        spec = json.loads(
            raw
        )

    except Exception as exc:

        raise ObsidureNativeToolingError(
            "NATIVE_EDIT_SPEC_INVALID_JSON"
        ) from exc


    if not isinstance(
        spec,
        dict,
    ):
        raise ObsidureNativeToolingError(
            "NATIVE_EDIT_SPEC_NOT_OBJECT"
        )


    return spec


def _validate_comment(
    value: Any,
) -> str:

    if not isinstance(
        value,
        str,
    ):
        raise ObsidureNativeToolingError(
            "NATIVE_COMMENT_NOT_TEXT"
        )

    comment = value.strip()

    if not comment:
        raise ObsidureNativeToolingError(
            "NATIVE_COMMENT_EMPTY"
        )

    if len(comment) > 160:
        raise ObsidureNativeToolingError(
            "NATIVE_COMMENT_TOO_LONG"
        )

    if "\n" in comment or "\r" in comment:
        raise ObsidureNativeToolingError(
            "NATIVE_COMMENT_MULTILINE_REJECTED"
        )

    if not re.fullmatch(
        r"[A-Za-z0-9 _.:/\-]+",
        comment,
    ):
        raise ObsidureNativeToolingError(
            "NATIVE_COMMENT_CHARSET_REJECTED"
        )

    return comment


def _insert_comment_after_docstring(
    source: str,
    comment: str,
) -> str:

    marker = (
        "# "
        + comment
    )

    if marker in source:
        raise ObsidureNativeToolingError(
            "NATIVE_EDIT_ALREADY_APPLIED"
        )


    try:
        tree = ast.parse(
            source
        )

    except SyntaxError as exc:

        raise ObsidureNativeToolingError(
            "NATIVE_SOURCE_SYNTAX_INVALID"
        ) from exc


    newline = (
        "\r\n"
        if "\r\n" in source
        else "\n"
    )


    lines = source.splitlines(
        keepends=True
    )


    insert_index = 0


    if tree.body:

        first = tree.body[0]

        is_docstring = (
            isinstance(
                first,
                ast.Expr,
            )
            and isinstance(
                first.value,
                ast.Constant,
            )
            and isinstance(
                first.value.value,
                str,
            )
        )

        if is_docstring:

            if first.end_lineno is None:
                raise ObsidureNativeToolingError(
                    "NATIVE_DOCSTRING_END_UNKNOWN"
                )

            insert_index = (
                first.end_lineno
            )


    lines.insert(
        insert_index,
        marker
        + newline,
    )


    generated = "".join(
        lines
    )


    try:
        ast.parse(
            generated
        )

    except SyntaxError as exc:

        raise ObsidureNativeToolingError(
            "NATIVE_GENERATED_SOURCE_INVALID"
        ) from exc


    return generated


def synthesize_native_source(
    context: BrodyNativeToolingContext,
) -> tuple[
    str,
    dict[str, Any],
]:

    _validate_target(
        context.target_path
    )


    spec = _extract_edit_spec(
        context.objective
    )


    operation = str(
        spec.get(
            "op",
            "",
        )
        or ""
    ).strip()


    if operation != (
        "insert_comment_after_docstring"
    ):
        raise ObsidureNativeToolingError(
            "NATIVE_OPERATION_UNSUPPORTED"
        )


    comment = _validate_comment(
        spec.get(
            "comment"
        )
    )


    generated = (
        _insert_comment_after_docstring(
            context.current_source,
            comment,
        )
    )


    if generated == context.current_source:
        raise ObsidureNativeToolingError(
            "NATIVE_GENERATION_NO_CHANGE"
        )


    metadata = {
        "strategy": (
            "INSERT_COMMENT_AFTER_MODULE_DOCSTRING"
        ),
        "brody_context_id": (
            context.context_id
        ),
        "brody_intent": (
            context.intent
        ),
        "brody_risk_flags": list(
            context.risk_flags
        ),
        "target_path": (
            context.target_path
        ),
        "base_sha": (
            context.base_sha
        ),
        "target_before_sha256": (
            context.target_before_sha256
        ),
        "prompt_sha256": (
            context.prompt_sha256
        ),
        "native_generation": True,
        "external_model": False,
        "deterministic": True,
        "backend_authority": "NONE",
        "decision_authority": (
            "KX108_ONLY"
        ),
        "memory_write": False,
        "kernel_mutation": False,
        "emits_act": False,
        "world_action": False,
    }


    return (
        generated,
        metadata,
    )


class ObsidureNativeToolingBackend:

    backend_id = BACKEND_ID


    def generate_text(
        self,
        prompt: str,
    ) -> ToolingBackendResult:

        try:
            context = (
                build_brody_native_tooling_context(
                    prompt
                )
            )

            generated, metadata = (
                synthesize_native_source(
                    context
                )
            )

        except ObsidureNativeToolingError:
            raise

        except Exception as exc:

            raise ObsidureNativeToolingError(
                "NATIVE_GENERATION_FAILED:"
                + type(exc).__name__
            ) from exc


        return ToolingBackendResult(
            backend_id=BACKEND_ID,
            model_id=MODEL_ID,
            output_text=generated,
            metadata=metadata,
        )


def self_check() -> dict[str, Any]:

    return {
        "backend_id": BACKEND_ID,
        "model_id": MODEL_ID,
        "role": (
            "NATIVE_ENGINEERING_SYNTHESIS"
        ),
        "current_strategy": (
            "INSERT_COMMENT_AFTER_MODULE_DOCSTRING"
        ),
        "native_generation": True,
        "external_model": False,
        "deterministic": True,
        "historical_agent_obsidure_modified": False,
        "historical_periphery_boundary_widened": False,
        "backend_authority": (
            OBSIDURE_AUTHORITY
        ),
        "decision_authority": (
            DECISION_AUTHORITY
        ),
        "filesystem_write": False,
        "network": False,
        "repo_mutation": False,
        "memory_write": False,
        "kernel_mutation": False,
        "emits_act": False,
        "auto_apply": False,
        "auto_commit": False,
        "push": False,
        "merge": False,
        "kx108_invoked": False,
        "world_action": False,
    }
